### ISSUE TITLE
where does this string appear ?

### ISSUE THREAD

**Issue by leela52452** [no-go/HaveRadiosion#4]
https://github.com/no-go/HaveRadiosion/blob/4869d21ec77805ed778bd2533accaa3c0fe35ae4/app/src/main/res/values/strings.xml#L8

i could not find in android 5.1 on 2.6 fdroid version

**Comment by alltagshack** [comment]
Hi leela, thank you for your translation!

Yes, you did not see it, because I hide it :-)
https://github.com/no-go/HaveRadiosion/blob/aa4ebbb05237034939fc46c64fb609c5d2b6ed43/app/src/main/java/click/dummer/have_radiosion/MainActivity.java#L243

Above 5.1 (Code M for Marshmallow 6.0) there is a special battery optimization mode in some devices. With this option, you can switch it off (if it makes problems). I hide this option on Android < 6.0
